const DB_KEY='ebook_esei_t4_v2';
const DEFAULT_PIN='1234';
let essays=loadData();
let mode='standard',currentId=essays[0]?.id||'',themeFilter='Semua',structureOn=true,currentEditId=null,currentImage='';
function loadData(){try{const raw=localStorage.getItem(DB_KEY);if(raw){const d=JSON.parse(raw);if(Array.isArray(d)&&d.length)return d}}catch(e){}localStorage.setItem(DB_KEY,JSON.stringify(seedEssays));return JSON.parse(JSON.stringify(seedEssays))}
function saveData(){localStorage.setItem(DB_KEY,JSON.stringify(essays))}
function uid(){return 'e'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function wc(text){return (text.trim().match(/[A-Za-zÀ-ÿ0-9'-]+/g)||[]).length}
function paras(text){return text.trim().split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)}
function sentenceSplit(s){return s.match(/[^.!?]+[.!?]?/g)?.map(x=>x.trim()).filter(Boolean)||[s]}
const simpleMap=[['persekolahan','sekolah'],['kediaman','rumah'],['menghidangkan','menyediakan'],['mengasingkan','memisahkan'],['menceriakan','mencantikkan'],['menggunakan','guna'],['meluangkan masa','berehat'],['pesisir pantai','tepi pantai'],['memastikan','pastikan'],['mengeratkan hubungan','menjadikan hubungan lebih rapat'],['sekiranya','jika'],['aktiviti rekreasi','aktiviti']];
function makeEasy(text){let ps=paras(text);return ps.map((p,i)=>{let t=p;simpleMap.forEach(([a,b])=>t=t.replace(new RegExp(a,'gi'),b));t=t.replace(/\btelah\b/gi,'').replace(/\s{2,}/g,' ');let ss=sentenceSplit(t);let out=[];ss.forEach(s=>{let words=s.split(/\s+/);if(words.length>15){let cut=-1;[' supaya ',' kerana ',' manakala ',' serta ',' dan '].some(c=>{let idx=s.toLowerCase().indexOf(c.trim());if(idx>20){cut=idx;return true}return false});if(cut>0){let a=s.slice(0,cut).trim().replace(/[,.]$/,'')+'.';let b=s.slice(cut).replace(/^(supaya|kerana|manakala|serta|dan)\s+/i,'').trim();if(b)b=b.charAt(0).toUpperCase()+b.slice(1).replace(/[.!?]?$/,'.');out.push(a,b)}else out.push(s)}else out.push(s)});return out.slice(0,2).join(' ')}).join('\n\n')}
function ensurePeriod(s){s=s.trim();return /[.!?]$/.test(s)?s:s+'.'}
function makeStandard(text){let ps=paras(text);let labels=['Pada masa yang sesuai, ','Mula-mula, ','Selain itu, ','Seterusnya, ','Kesimpulannya, '];let result=ps.map((p,i)=>{let s=ensurePeriod(p);if(i>0&&i<ps.length-1&&!/^(Mula-mula|Selain itu|Seterusnya|Di samping itu|Kemudian)/i.test(s))s=labels[Math.min(i,3)]+s.charAt(0).toLowerCase()+s.slice(1);if(i===ps.length-1&&!/^Kesimpulannya/i.test(s))s='Kesimpulannya, '+s.charAt(0).toLowerCase()+s.slice(1);return s});let joined=result.join('\n\n');let count=wc(joined);const adders=['Aktiviti ini dilakukan dengan baik dan teratur.','Hal ini dapat memberikan banyak manfaat kepada kita.','Kita juga perlu melakukan perkara ini dengan penuh tanggungjawab.','Amalan yang baik ini wajar diteruskan dalam kehidupan harian.'];let idx=0;while(count<80&&result.length>1&&idx<8){let pos=Math.min(1+(idx%(Math.max(1,result.length-1))),result.length-1);result[pos]=result[pos]+' '+adders[idx%adders.length];joined=result.join('\n\n');count=wc(joined);idx++}if(count>105){joined=result.map(p=>sentenceSplit(p).slice(0,2).join(' ')).join('\n\n')}return joined}
function autoGenerateMissing(){const e=document.getElementById('fEasy'),s=document.getElementById('fStandard');let changed=false;if(!e.value.trim()&&s.value.trim()){e.value=makeEasy(s.value);document.getElementById('easyAuto').classList.remove('hidden');changed=true}if(!s.value.trim()&&e.value.trim()){s.value=makeStandard(e.value);document.getElementById('standardAuto').classList.remove('hidden');changed=true}if(!changed)toast('Kedua-dua versi sudah ada atau masih kosong.')}
function renderThemes(){const bar=document.getElementById('themeBar');const themes=['Semua',...new Set(essays.map(x=>x.theme).filter(Boolean))];bar.innerHTML=themes.map(t=>`<button class="${t===themeFilter?'on':''}" data-theme="${esc(t)}">${esc(t)}</button>`).join('');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{themeFilter=b.dataset.theme;renderStudent()})}
function filtered(){const q=document.getElementById('searchInput').value.trim().toLowerCase();return essays.filter(e=>(themeFilter==='Semua'||e.theme===themeFilter)&&(!q||(`${e.title} ${e.theme}`).toLowerCase().includes(q)))}
function renderStudent(){document.getElementById('essayCount').textContent=essays.length;renderThemes();const list=filtered();if(!list.some(x=>x.id===currentId))currentId=list[0]?.id||'';document.getElementById('essayList').innerHTML=list.map(e=>`<button class="essay-item ${e.id===currentId?'on':''}" data-id="${e.id}"><b>${esc(e.title)}</b><small>${esc(e.theme||'Tanpa tema')}</small></button>`).join('')||'<div style="padding:12px;color:#7b8794">Tiada karangan ditemui.</div>';document.querySelectorAll('.essay-item').forEach(b=>b.onclick=()=>{currentId=b.dataset.id;renderStudent()});const e=essays.find(x=>x.id===currentId);if(!e){document.getElementById('essayTitle').textContent='Tiada karangan';document.getElementById('essayPaper').innerHTML='';return}document.getElementById('essayTheme').textContent=e.theme||'Tanpa tema';document.getElementById('essayTitle').textContent=e.title;let text=(mode==='easy'?e.easy:e.standard)||'';document.getElementById('wordCount').textContent=wc(text)+' patah perkataan';document.getElementById('versionInfo').textContent=mode==='easy'?'Versi Mudah':'Versi Standard';const wrap=document.getElementById('imageWrap');wrap.innerHTML=e.image?`<img src="${e.image}" alt="Grafik ${esc(e.title)}">`:'<div class="image-placeholder"><b>Grafik belum dimuat naik</b>Guru boleh menambah imej melalui Mod Guru.</div>';const labs=['Pendahuluan','Isi 1','Isi 2','Isi 3','Penutup'];document.getElementById('essayPaper').innerHTML=paras(text).map((p,i)=>`<p>${structureOn&&i<5?`<span class="structure-label">${labs[i]}</span><br>`:''}${esc(p)}</p>`).join('');document.getElementById('standardBtn').classList.toggle('on',mode==='standard');document.getElementById('easyBtn').classList.toggle('on',mode==='easy');document.getElementById('structureBtn').textContent='Struktur '+(structureOn?'ON':'OFF')}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showStudent(){document.getElementById('studentView').classList.remove('hidden');document.getElementById('teacherView').classList.add('hidden');document.getElementById('studentModeBtn').classList.add('primary');document.getElementById('teacherModeBtn').classList.remove('primary');renderStudent()}
function requestTeacher(){document.getElementById('pinModal').classList.add('show');document.getElementById('pinInput').value='';setTimeout(()=>document.getElementById('pinInput').focus(),50)}
function showTeacher(){document.getElementById('pinModal').classList.remove('show');document.getElementById('studentView').classList.add('hidden');document.getElementById('teacherView').classList.remove('hidden');document.getElementById('teacherModeBtn').classList.add('primary');document.getElementById('studentModeBtn').classList.remove('primary');renderTeacherList();if(currentEditId)loadEditor(currentEditId);else newEssay()}
function renderTeacherList(){const box=document.getElementById('teacherList');box.innerHTML=essays.map(e=>`<div class="teacher-row ${e.id===currentEditId?'on':''}"><b>${esc(e.title)}</b><small>${esc(e.theme||'Tanpa tema')}</small><div class="row-actions"><button class="btn small" data-edit="${e.id}">Edit</button><button class="btn danger small" data-del="${e.id}">Padam</button></div></div>`).join('');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>loadEditor(b.dataset.edit));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteById(b.dataset.del))}
function resetAutoBadges(){document.getElementById('easyAuto').classList.add('hidden');document.getElementById('standardAuto').classList.add('hidden')}
function newEssay(){currentEditId=null;currentImage='';document.getElementById('fTitle').value='';document.getElementById('fTheme').value='';document.getElementById('fEasy').value='';document.getElementById('fStandard').value='';document.getElementById('fImage').value='';document.getElementById('imagePreview').innerHTML='<span style="color:#8b96a3">Tiada imej dipilih</span>';resetAutoBadges();renderTeacherList();setStatus('',false)}
function loadEditor(id){const e=essays.find(x=>x.id===id);if(!e)return;currentEditId=id;currentImage=e.image||'';document.getElementById('fTitle').value=e.title||'';document.getElementById('fTheme').value=e.theme||'';document.getElementById('fEasy').value=e.easy||'';document.getElementById('fStandard').value=e.standard||'';document.getElementById('fImage').value='';document.getElementById('imagePreview').innerHTML=currentImage?`<img src="${currentImage}" alt="Pratonton">`:'<span style="color:#8b96a3">Tiada imej dipilih</span>';resetAutoBadges();renderTeacherList();setStatus('',false)}
function setStatus(msg,ok=true){const s=document.getElementById('editorStatus');if(!msg){s.className='status';s.textContent='';return}s.textContent=msg;s.className='status show '+(ok?'ok':'bad')}
function saveEditor(){let title=document.getElementById('fTitle').value.trim(),theme=document.getElementById('fTheme').value.trim(),easy=document.getElementById('fEasy').value.trim(),standard=document.getElementById('fStandard').value.trim();if(!title){setStatus('Sila masukkan tajuk.',false);return}if(!easy&&!standard){setStatus('Masukkan sekurang-kurangnya satu versi karangan.',false);return}if(!easy){easy=makeEasy(standard);document.getElementById('fEasy').value=easy;document.getElementById('easyAuto').classList.remove('hidden')}if(!standard){standard=makeStandard(easy);document.getElementById('fStandard').value=standard;document.getElementById('standardAuto').classList.remove('hidden')}let obj={id:currentEditId||uid(),title,theme,image:currentImage,easy,standard};if(currentEditId){const i=essays.findIndex(x=>x.id===currentEditId);essays[i]=obj}else{essays.push(obj);currentEditId=obj.id}saveData();renderTeacherList();renderStudent();setStatus(`Disimpan. Mudah: ${wc(easy)} perkataan · Standard: ${wc(standard)} perkataan`,true)}
function deleteById(id){const e=essays.find(x=>x.id===id);if(!e)return;if(!confirm(`Padam “${e.title}”?`))return;essays=essays.filter(x=>x.id!==id);saveData();if(currentId===id)currentId=essays[0]?.id||'';if(currentEditId===id)newEssay();renderTeacherList();renderStudent();toast('Karangan dipadam.')}
function handleImage(file){if(!file)return;if(file.size>2.5*1024*1024){setStatus('Imej terlalu besar. Gunakan imej bawah 2.5 MB.',false);return}const r=new FileReader();r.onload=()=>{currentImage=r.result;document.getElementById('imagePreview').innerHTML=`<img src="${currentImage}" alt="Pratonton">`};r.readAsDataURL(file)}
function exportData(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),essays},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ebook-karangan-tahun4-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);const arr=Array.isArray(d)?d:d.essays;if(!Array.isArray(arr))throw new Error('format');if(!confirm(`Import ${arr.length} karangan dan gantikan data semasa?`))return;essays=arr;saveData();currentId=essays[0]?.id||'';currentEditId=null;renderTeacherList();renderStudent();newEssay();toast('Import berjaya.')}catch(e){alert('Fail JSON tidak sah.')}};r.readAsText(file)}
function previewCurrent(){let title=document.getElementById('fTitle').value.trim(),theme=document.getElementById('fTheme').value.trim(),easy=document.getElementById('fEasy').value.trim(),standard=document.getElementById('fStandard').value.trim();if(!title||(!easy&&!standard)){setStatus('Masukkan tajuk dan sekurang-kurangnya satu versi dahulu.',false);return}if(!easy)easy=makeEasy(standard);if(!standard)standard=makeStandard(easy);const temp={id:'__preview__',title,theme,image:currentImage,easy,standard};const old=essays.findIndex(x=>x.id==='__preview__');if(old>=0)essays.splice(old,1);essays.unshift(temp);currentId='__preview__';showStudent();toast('Pratonton sementara. Simpan melalui Mod Guru jika berpuas hati.')}
function cleanupPreview(){const i=essays.findIndex(x=>x.id==='__preview__');if(i>=0){essays.splice(i,1);if(currentId==='__preview__')currentId=essays[0]?.id||''}}
document.getElementById('studentModeBtn').onclick=()=>{cleanupPreview();showStudent()};
document.getElementById('teacherModeBtn').onclick=requestTeacher;
document.getElementById('pinCancel').onclick=()=>document.getElementById('pinModal').classList.remove('show');
document.getElementById('pinOk').onclick=()=>{const ok=document.getElementById('pinInput').value===DEFAULT_PIN;if(ok){showTeacher()}else{const s=document.getElementById('pinStatus');s.textContent='PIN salah.';s.className='status show bad'}};
document.getElementById('pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('pinOk').click()});
document.getElementById('standardBtn').onclick=()=>{mode='standard';renderStudent()};document.getElementById('easyBtn').onclick=()=>{mode='easy';renderStudent()};document.getElementById('structureBtn').onclick=()=>{structureOn=!structureOn;renderStudent()};document.getElementById('fontBtn').onclick=()=>document.body.classList.toggle('big');document.getElementById('printBtn').onclick=()=>window.print();document.getElementById('searchInput').oninput=renderStudent;
document.getElementById('prevBtn').onclick=()=>{const arr=filtered(),i=arr.findIndex(x=>x.id===currentId);if(arr.length){currentId=arr[(i-1+arr.length)%arr.length].id;renderStudent()}};document.getElementById('nextBtn').onclick=()=>{const arr=filtered(),i=arr.findIndex(x=>x.id===currentId);if(arr.length){currentId=arr[(i+1)%arr.length].id;renderStudent()}};
document.getElementById('newEssayBtn').onclick=newEssay;document.getElementById('generateMissingBtn').onclick=autoGenerateMissing;document.getElementById('saveEssayBtn').onclick=saveEditor;document.getElementById('deleteEssayBtn').onclick=()=>currentEditId?deleteById(currentEditId):newEssay();document.getElementById('previewStudentBtn').onclick=previewCurrent;document.getElementById('fImage').onchange=e=>handleImage(e.target.files[0]);document.getElementById('removeImageBtn').onclick=()=>{currentImage='';document.getElementById('fImage').value='';document.getElementById('imagePreview').innerHTML='<span style="color:#8b96a3">Tiada imej dipilih</span>'};document.getElementById('exportBtn').onclick=exportData;document.getElementById('importInput').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};
renderStudent();
